<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sara S">

<title>A2-Part I – My-Blog</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">My-Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">A2-Part I</h1>
            <p class="subtitle lead">Movie Profits</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Sara S </p>
            </div>
    </div>
      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="dataset-movie-profits" class="level1">
<h1>Dataset: Movie Profits</h1>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>In this analysis, we explore the profitability of movies based on a dataset containing information about production budgets, gross earnings, and various qualitative aspects of films. The primary objective is to assess which genres yield the highest profit and to analyze how different factors such as release dates, distributors, and ratings contribute to movie success.</p>
</section>
<section id="installing-packages" class="level2">
<h2 class="anchored" data-anchor-id="installing-packages">Installing Packages</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'mosaic':
  method                           from   
  fortify.SpatialPolygonsDataFrame ggplot2

The 'mosaic' package masks several functions from core packages in order to add 
additional features.  The original behavior of these functions should not be affected by this.

Attaching package: 'mosaic'

The following object is masked from 'package:Matrix':

    mean

The following objects are masked from 'package:dplyr':

    count, do, tally

The following object is masked from 'package:purrr':

    cross

The following object is masked from 'package:ggplot2':

    stat

The following objects are masked from 'package:stats':

    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,
    quantile, sd, t.test, var

The following objects are masked from 'package:base':

    max, mean, min, prod, range, sample, sum</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'skimr'

The following object is masked from 'package:mosaic':

    n_missing</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggformula)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="importing-the-dataset" class="level2">
<h2 class="anchored" data-anchor-id="importing-the-dataset">Importing the dataset</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>movies <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="st">"../../data/movie_profit.csv"</span>, <span class="at">delim =</span> <span class="st">";"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 3310 Columns: 10
── Column specification ────────────────────────────────────────────────────────
Delimiter: ";"
chr  (4): movie, distributor, mpaa_rating, genre
dbl  (4): production_budget, domestic_gross, worldwide_gross, decade
num  (1): profit_ratio
date (1): release_date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>movies</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3,310 × 10
   release_date movie           production_budget domestic_gross worldwide_gross
   &lt;date&gt;       &lt;chr&gt;                       &lt;dbl&gt;          &lt;dbl&gt;           &lt;dbl&gt;
 1 2005-07-22   November                   250000         191862          191862
 2 1998-08-28   I Married a St…            250000         203134          203134
 3 1997-03-28   Love and Other…            250000         212285          743216
 4 2000-07-14   Chuck&amp;Buck                 250000        1055671         1157672
 5 2011-10-28   Like Crazy                 250000        3395391         3728400
 6 2003-04-11   Better Luck To…            250000        3802390         3809226
 7 2017-04-28   Sleight                    250000        3930990         3934450
 8 2002-06-28   Lovely and Ama…            250000        4210379         4613482
 9 2012-08-17   Compliance                 270000         319285          830700
10 2005-05-06   Fighting Tommy…            300000          10514           10514
# ℹ 3,300 more rows
# ℹ 5 more variables: distributor &lt;chr&gt;, mpaa_rating &lt;chr&gt;, genre &lt;chr&gt;,
#   profit_ratio &lt;dbl&gt;, decade &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="organizing-the-data" class="level2">
<h2 class="anchored" data-anchor-id="organizing-the-data">Organizing the data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(movies)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 3,310
Columns: 10
$ release_date      &lt;date&gt; 2005-07-22, 1998-08-28, 1997-03-28, 2000-07-14, 201…
$ movie             &lt;chr&gt; "November", "I Married a Strange Person", "Love and …
$ production_budget &lt;dbl&gt; 250000, 250000, 250000, 250000, 250000, 250000, 2500…
$ domestic_gross    &lt;dbl&gt; 191862, 203134, 212285, 1055671, 3395391, 3802390, 3…
$ worldwide_gross   &lt;dbl&gt; 191862, 203134, 743216, 1157672, 3728400, 3809226, 3…
$ distributor       &lt;chr&gt; "Other", "Other", "Other", "Other", "Paramount&nbsp;Pictu…
$ mpaa_rating       &lt;chr&gt; "R", NA, "R", "R", "PG-13", "R", "R", "R", "R", "R",…
$ genre             &lt;chr&gt; "Drama", "Comedy", "Comedy", "Drama", "Drama", "Dram…
$ profit_ratio      &lt;dbl&gt; 7.674480e+13, 8.125360e+13, 2.972864e+14, 4.630688e+…
$ decade            &lt;dbl&gt; 2000, 1990, 1990, 2000, 2010, 2000, 2010, 2000, 2010…</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">inspect</span>(movies)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
categorical variables:  
         name     class levels    n missing
1       movie character   3310 3310       0
2 distributor character      6 3268      42
3 mpaa_rating character      4 3180     130
4       genre character      5 3310       0
                                   distribution
1 10 Days in a Madhouse (0%) ...               
2  Other (53.2%), Warner&nbsp;Bros. (11%) ...       
3 R (46.4%), PG-13 (33.5%), PG (17.4%) ...     
4 Drama (36.5%), Comedy (24.1%) ...            

Date variables:  
          name class      first       last min_diff  max_diff    n missing
1 release_date  Date 1936-02-05 2017-12-22   0 days 2592 days 3310       0

quantitative variables:  
               name   class      min           Q1       median           Q3
1 production_budget numeric 2.50e+05 9.500000e+06 2.000000e+07 4.500000e+07
2    domestic_gross numeric 0.00e+00 6.530094e+06 2.558731e+07 6.046695e+07
3   worldwide_gross numeric 4.23e+02 1.086144e+07 4.040903e+07 1.184703e+08
4      profit_ratio numeric 1.38e+10 7.861269e+13 1.962499e+14 3.942158e+14
5            decade numeric 1.93e+03 1.990000e+03 2.000000e+03 2.010000e+03
           max         mean           sd    n missing
1 1.750000e+08 3.326794e+07 3.460741e+07 3310       0
2 4.745447e+08 4.551509e+07 5.852794e+07 3310       0
3 1.162782e+09 9.384123e+07 1.389514e+08 3310       0
4 4.315179e+16 4.319388e+14 1.501736e+15 3310       0
5 2.010000e+03 1.998785e+03 1.061308e+01 3310       0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(movies)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">movies</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">3310</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Date</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">movie</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3310</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">distributor</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mpaa_rating</td>
<td style="text-align: right;">130</td>
<td style="text-align: right;">0.96</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">genre</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: Date</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 12%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: left;">min</th>
<th style="text-align: left;">max</th>
<th style="text-align: left;">median</th>
<th style="text-align: right;">n_unique</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">release_date</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">1936-02-05</td>
<td style="text-align: left;">2017-12-22</td>
<td style="text-align: left;">2005-06-30</td>
<td style="text-align: right;">1723</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 13%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">production_budget</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.326794e+07</td>
<td style="text-align: right;">3.460741e+07</td>
<td style="text-align: right;">2.50e+05</td>
<td style="text-align: right;">9.500000e+06</td>
<td style="text-align: right;">2.000000e+07</td>
<td style="text-align: right;">4.500000e+07</td>
<td style="text-align: right;">1.750000e+08</td>
<td style="text-align: left;">▇▂▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">domestic_gross</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.551509e+07</td>
<td style="text-align: right;">5.852794e+07</td>
<td style="text-align: right;">0.00e+00</td>
<td style="text-align: right;">6.530094e+06</td>
<td style="text-align: right;">2.558731e+07</td>
<td style="text-align: right;">6.046695e+07</td>
<td style="text-align: right;">4.745447e+08</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">worldwide_gross</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">9.384123e+07</td>
<td style="text-align: right;">1.389514e+08</td>
<td style="text-align: right;">4.23e+02</td>
<td style="text-align: right;">1.086144e+07</td>
<td style="text-align: right;">4.040903e+07</td>
<td style="text-align: right;">1.184703e+08</td>
<td style="text-align: right;">1.162782e+09</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">profit_ratio</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.319388e+14</td>
<td style="text-align: right;">1.501736e+15</td>
<td style="text-align: right;">1.38e+10</td>
<td style="text-align: right;">7.861269e+13</td>
<td style="text-align: right;">1.962499e+14</td>
<td style="text-align: right;">3.942158e+14</td>
<td style="text-align: right;">4.315179e+16</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">decade</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.998790e+03</td>
<td style="text-align: right;">1.061000e+01</td>
<td style="text-align: right;">1.93e+03</td>
<td style="text-align: right;">1.990000e+03</td>
<td style="text-align: right;">2.000000e+03</td>
<td style="text-align: right;">2.010000e+03</td>
<td style="text-align: right;">2.010000e+03</td>
<td style="text-align: left;">▁▁▁▃▇</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="data-dictionary" class="level2">
<h2 class="anchored" data-anchor-id="data-dictionary">Data Dictionary</h2>
<section id="quantitative-variables" class="level3">
<h3 class="anchored" data-anchor-id="quantitative-variables">Quantitative Variables:</h3>
<ul>
<li><p><strong>production_budget</strong> (&lt;dbl&gt;): The cost of producing the movie.</p></li>
<li><p><strong>domestic_gross</strong> (&lt;dbl&gt;): Revenue earned from domestic markets.</p></li>
<li><p><strong>worldwide_gross</strong> (&lt;dbl&gt;): Total revenue earned from all markets.</p></li>
<li><p><strong>profit_ratio</strong> (&lt;dbl&gt;): The ratio of profit, calculated based on budget and gross earnings.</p></li>
</ul>
</section>
<section id="qualitative-variables" class="level3">
<h3 class="anchored" data-anchor-id="qualitative-variables">Qualitative Variables:</h3>
<ul>
<li><p><strong>release_date</strong> (&lt;date&gt;): The date the movie was released.</p></li>
<li><p><strong>decade</strong> (&lt;dbl&gt;): The decade in which the movie was released, derived from the date of release.</p></li>
<li><p><strong>movie</strong> (&lt;chr&gt;): The name of the movie.</p></li>
<li><p><strong>distributor</strong> (&lt;chr&gt;): The company that distributed the movie.</p></li>
<li><p><strong>mpaa_rating</strong> (&lt;chr&gt;): The movie’s rating like PG-18, PG-13.</p></li>
<li><p><strong>genre</strong> (&lt;chr&gt;): The genre of the movie such as drama, comedy and action.</p></li>
</ul>
</section>
</section>
<section id="factorization" class="level2">
<h2 class="anchored" data-anchor-id="factorization">Factorization</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>movies_modified <span class="ot">&lt;-</span> movies <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">decade =</span> <span class="fu">as_factor</span>(decade),</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">genre =</span> <span class="fu">as_factor</span>(genre),</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mpaa_rating =</span> <span class="fu">as_factor</span>(mpaa_rating),</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">distributor =</span> <span class="fu">as_factor</span>(distributor)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(movies_modified)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 3,310
Columns: 10
$ release_date      &lt;date&gt; 2005-07-22, 1998-08-28, 1997-03-28, 2000-07-14, 201…
$ movie             &lt;chr&gt; "November", "I Married a Strange Person", "Love and …
$ production_budget &lt;dbl&gt; 250000, 250000, 250000, 250000, 250000, 250000, 2500…
$ domestic_gross    &lt;dbl&gt; 191862, 203134, 212285, 1055671, 3395391, 3802390, 3…
$ worldwide_gross   &lt;dbl&gt; 191862, 203134, 743216, 1157672, 3728400, 3809226, 3…
$ distributor       &lt;fct&gt; Other, Other, Other, Other, Paramount&nbsp;Pictures, Para…
$ mpaa_rating       &lt;fct&gt; R, NA, R, R, PG-13, R, R, R, R, R, R, R, PG-13, NA, …
$ genre             &lt;fct&gt; Drama, Comedy, Comedy, Drama, Drama, Drama, Action, …
$ profit_ratio      &lt;dbl&gt; 7.674480e+13, 8.125360e+13, 2.972864e+14, 4.630688e+…
$ decade            &lt;fct&gt; 2000, 1990, 1990, 2000, 2010, 2000, 2010, 2000, 2010…</code></pre>
</div>
</div>
<pre><code></code></pre>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">inspect</span>(movies_modified)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
categorical variables:  
         name     class levels    n missing
1       movie character   3310 3310       0
2 distributor    factor      6 3268      42
3 mpaa_rating    factor      4 3180     130
4       genre    factor      5 3310       0
5      decade    factor      9 3310       0
                                   distribution
1 10 Days in a Madhouse (0%) ...               
2  Other (53.2%), Warner&nbsp;Bros. (11%) ...       
3 R (46.4%), PG-13 (33.5%), PG (17.4%) ...     
4 Drama (36.5%), Comedy (24.1%) ...            
5 2000 (41.9%), 2010 (30%) ...                 

Date variables:  
          name class      first       last min_diff  max_diff    n missing
1 release_date  Date 1936-02-05 2017-12-22   0 days 2592 days 3310       0

quantitative variables:  
               name   class      min           Q1       median           Q3
1 production_budget numeric 2.50e+05 9.500000e+06 2.000000e+07 4.500000e+07
2    domestic_gross numeric 0.00e+00 6.530094e+06 2.558731e+07 6.046695e+07
3   worldwide_gross numeric 4.23e+02 1.086144e+07 4.040903e+07 1.184703e+08
4      profit_ratio numeric 1.38e+10 7.861269e+13 1.962499e+14 3.942158e+14
           max         mean           sd    n missing
1 1.750000e+08 3.326794e+07 3.460741e+07 3310       0
2 4.745447e+08 4.551509e+07 5.852794e+07 3310       0
3 1.162782e+09 9.384123e+07 1.389514e+08 3310       0
4 4.315179e+16 4.319388e+14 1.501736e+15 3310       0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(movies_modified)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">movies_modified</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">3310</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Date</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">factor</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">movie</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3310</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: Date</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 12%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: left;">min</th>
<th style="text-align: left;">max</th>
<th style="text-align: left;">median</th>
<th style="text-align: right;">n_unique</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">release_date</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">1936-02-05</td>
<td style="text-align: left;">2017-12-22</td>
<td style="text-align: left;">2005-06-30</td>
<td style="text-align: right;">1723</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: left;">ordered</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: left;">top_counts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">distributor</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Oth: 1737, War: 360, Son: 332, Uni: 299</td>
</tr>
<tr class="even">
<td style="text-align: left;">mpaa_rating</td>
<td style="text-align: right;">130</td>
<td style="text-align: right;">0.96</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">R: 1477, PG-: 1066, PG: 552, G: 85</td>
</tr>
<tr class="odd">
<td style="text-align: left;">genre</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">Dra: 1209, Com: 798, Act: 547, Adv: 467</td>
</tr>
<tr class="even">
<td style="text-align: left;">decade</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">200: 1387, 201: 994, 199: 607, 198: 228</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 13%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">production_budget</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.326794e+07</td>
<td style="text-align: right;">3.460741e+07</td>
<td style="text-align: right;">2.50e+05</td>
<td style="text-align: right;">9.500000e+06</td>
<td style="text-align: right;">2.000000e+07</td>
<td style="text-align: right;">4.500000e+07</td>
<td style="text-align: right;">1.750000e+08</td>
<td style="text-align: left;">▇▂▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">domestic_gross</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.551509e+07</td>
<td style="text-align: right;">5.852794e+07</td>
<td style="text-align: right;">0.00e+00</td>
<td style="text-align: right;">6.530094e+06</td>
<td style="text-align: right;">2.558731e+07</td>
<td style="text-align: right;">6.046695e+07</td>
<td style="text-align: right;">4.745447e+08</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">worldwide_gross</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">9.384123e+07</td>
<td style="text-align: right;">1.389514e+08</td>
<td style="text-align: right;">4.23e+02</td>
<td style="text-align: right;">1.086144e+07</td>
<td style="text-align: right;">4.040903e+07</td>
<td style="text-align: right;">1.184703e+08</td>
<td style="text-align: right;">1.162782e+09</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">profit_ratio</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.319388e+14</td>
<td style="text-align: right;">1.501736e+15</td>
<td style="text-align: right;">1.38e+10</td>
<td style="text-align: right;">7.861269e+13</td>
<td style="text-align: right;">1.962499e+14</td>
<td style="text-align: right;">3.942158e+14</td>
<td style="text-align: right;">4.315179e+16</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="target-variable" class="level2">
<h2 class="anchored" data-anchor-id="target-variable">Target Variable</h2>
<p>The target variable, also known as the dependent variable, is the main outcome that can be used to predict or explain the analysis. It is the primary focus of a dataset. The target variable for the movie profit dataset. The ratio of profit is calculated based on budget and gross earnings. This variable indicates how profitable the movie was, which is often the key metric for movie success.</p>
</section>
<section id="predictor-variable" class="level2">
<h2 class="anchored" data-anchor-id="predictor-variable">Predictor Variable</h2>
<p>Predictor variables, or independent variables, are the features or inputs used to make predictions about the target variable. These variables influence or relate to the target variable. The predictor variables for the movie profit dataset are as follows:</p>
<ul>
<li><p><strong>production_budget</strong></p></li>
<li><p><strong>domestic_gross</strong></p></li>
<li><p><strong>worldwide_gross</strong></p></li>
<li><p><strong>release_date</strong></p></li>
<li><p><strong>decade</strong></p></li>
<li><p><strong>mpaa_rating</strong></p></li>
<li><p><strong>distributor</strong></p></li>
<li><p><strong>genre</strong></p></li>
</ul>
</section>
<section id="analyse-the-qualitative-data" class="level2">
<h2 class="anchored" data-anchor-id="analyse-the-qualitative-data">Analyse the qualitative data</h2>
<section id="date-of-release" class="level3">
<h3 class="anchored" data-anchor-id="date-of-release">Date of release</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>movies_modified <span class="sc">%&gt;%</span> <span class="fu">count</span>(release_date)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,723 × 2
   release_date     n
   &lt;date&gt;       &lt;int&gt;
 1 1936-02-05       1
 2 1939-12-15       1
 3 1940-02-09       1
 4 1942-08-13       1
 5 1943-01-23       1
 6 1946-01-01       1
 7 1953-02-05       1
 8 1954-12-23       1
 9 1956-02-16       1
10 1956-10-17       1
# ℹ 1,713 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>movies_modified <span class="sc">%&gt;%</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(release_date) <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,723 × 2
   release_date     n
   &lt;date&gt;       &lt;int&gt;
 1 2000-12-22       8
 2 2005-09-30       7
 3 2010-10-08       7
 4 2011-07-29       7
 5 1998-11-20       6
 6 2002-10-25       6
 7 2005-10-21       6
 8 2006-04-28       6
 9 2006-08-11       6
10 2006-09-22       6
# ℹ 1,713 more rows</code></pre>
</div>
</div>
<section id="observations" class="level4">
<h4 class="anchored" data-anchor-id="observations">Observations:</h4>
<p>This analysis counts the number of movies released on specific dates. Typically, most movies have unique release dates, so we can expect that the counts for individual release_dates values are 1 or at most below three during the late 20th century, with only a few films sharing the same date. However, it became increasingly common for multiple films to be released on the same date since the 2000s, with up to 8 movies being released in December of 2000. The results can help identify peak movie release periods used by the film industry.</p>
</section>
</section>
<section id="decade" class="level3">
<h3 class="anchored" data-anchor-id="decade">Decade</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>movies_modified <span class="sc">%&gt;%</span> <span class="fu">count</span>(decade)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 2
  decade     n
  &lt;fct&gt;  &lt;int&gt;
1 1930       2
2 1940       4
3 1950       6
4 1960      19
5 1970      63
6 1980     228
7 1990     607
8 2000    1387
9 2010     994</code></pre>
</div>
</div>
<section id="observations-1" class="level4">
<h4 class="anchored" data-anchor-id="observations-1">Observations:</h4>
<p>By counting the number of movies released in each decade, we can identify which decades had the highest number of releases according to the dataset. This trend indicates growth in the industry and its production capabilities, evident during the 1990s, 2000s, and 2010s, which highlight improved production resources and greater accessibility to films.</p>
</section>
</section>
<section id="movie" class="level3">
<h3 class="anchored" data-anchor-id="movie">Movie</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>movies_modified <span class="sc">%&gt;%</span> <span class="fu">count</span>(movie)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3,310 × 2
   movie                     n
   &lt;chr&gt;                 &lt;int&gt;
 1 10 Days in a Madhouse     1
 2 10,000 B.C.               1
 3 102 Dalmatians            1
 4 12 Rounds                 1
 5 12 Years a Slave          1
 6 127 Hours                 1
 7 13 Going On 30            1
 8 16 Blocks                 1
 9 17 Again                  1
10 2 Fast 2 Furious          1
# ℹ 3,300 more rows</code></pre>
</div>
</div>
<section id="observations-2" class="level4">
<h4 class="anchored" data-anchor-id="observations-2">Observations:</h4>
<p>This analysis counts the occurrences of each movie in the dataset. Most films should appear only once, resulting in counts of one for each entry.</p>
</section>
</section>
<section id="distributor" class="level3">
<h3 class="anchored" data-anchor-id="distributor">Distributor</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>movies_modified <span class="sc">%&gt;%</span> <span class="fu">count</span>(distributor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 2
  distributor            n
  &lt;fct&gt;              &lt;int&gt;
1 Other               1737
2 Paramount&nbsp;Pictures   261
3 Universal            299
4 20th&nbsp;Century&nbsp;Fox     279
5 Sony&nbsp;Pictures        332
6 Warner&nbsp;Bros.         360
7 &lt;NA&gt;                  42</code></pre>
</div>
</div>
<section id="observations-3" class="level4">
<h4 class="anchored" data-anchor-id="observations-3">Observations:</h4>
<p>This analysis is done to understand the number of movies managed by each company. The table reveals that the category Other dominates the dataset with 1,737 films, indicating a significant presence of smaller or independent distributors. Among major studios, Warner Bros.&nbsp;leads with 360 films, followed by Sony Pictures at 332, Universal at 299, 20th Century Fox at 279 and finally Paramount Pictures at 261 films, highlighting their relevance in the industry. Overall, the dataset features a mix of both major and minor distributors, with a higher number for the Other category (200 more than the films of major studies combined), suggesting a diverse range of films, including independent productions and those distributed outside traditional channels.</p>
</section>
</section>
<section id="rating" class="level3">
<h3 class="anchored" data-anchor-id="rating">Rating</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>movies_modified <span class="sc">%&gt;%</span> <span class="fu">count</span>(mpaa_rating)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  mpaa_rating     n
  &lt;fct&gt;       &lt;int&gt;
1 R            1477
2 PG-13        1066
3 PG            552
4 G              85
5 &lt;NA&gt;          130</code></pre>
</div>
</div>
<section id="observations-4" class="level4">
<h4 class="anchored" data-anchor-id="observations-4">Observations:</h4>
<p>The analysis of MPAA ratings shows how movies are classified based on their intended audience. The dataset indicates that there are many R-rated films, with a total of 1,477, and a close number of PG-13 films at 1,066. On the other hand, there are 552 PG-rated films, and G-rated films are the least common, with only 85 entries. This indicates that the majority of films are targeted toward mature audiences, reflecting trends in content production that cater to more adult themes, while very few films are suitable for all ages without parental guidance.</p>
</section>
</section>
<section id="genre" class="level3">
<h3 class="anchored" data-anchor-id="genre">Genre</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>movies_modified <span class="sc">%&gt;%</span> <span class="fu">count</span>(genre)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  genre         n
  &lt;fct&gt;     &lt;int&gt;
1 Drama      1209
2 Comedy      798
3 Action      547
4 Horror      289
5 Adventure   467</code></pre>
</div>
</div>
<section id="observations-5" class="level4">
<h4 class="anchored" data-anchor-id="observations-5">Observations:</h4>
<p>The distribution of films across various categories reveals that the drama genre emerges as the most popular one, with 1,209 entries, followed by Comedy at 798. Action and Adventure films also contribute significantly, about 547 and 467 entries respectively, indicating their popularity and frequent production. Surprisingly, horror is the least represented genre, with only about 289 films, despite its popularity, especially around Halloween in October</p>
</section>
</section>
</section>
<section id="analayse-the-quantitative-data" class="level2">
<h2 class="anchored" data-anchor-id="analayse-the-quantitative-data">Analayse the quantitative data</h2>
<section id="production-budget" class="level3">
<h3 class="anchored" data-anchor-id="production-budget">Production budget</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>movies_modified <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_histogram</span>(<span class="sc">~</span>production_budget)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="observations-6" class="level4">
<h4 class="anchored" data-anchor-id="observations-6">Observations:</h4>
<p>The histogram of production budgets reveals a right-skewed distribution, indicating that most films have lower budgets. A significant number of movies fall within the lower budget range, while high-budget films are less common. This implies that filmmakers often work with limited financial resources.</p>
</section>
</section>
<section id="domestic-gross" class="level3">
<h3 class="anchored" data-anchor-id="domestic-gross">Domestic gross</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>movies_modified <span class="sc">%&gt;%</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_histogram</span>(<span class="sc">~</span>domestic_gross)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="observations-7" class="level4">
<h4 class="anchored" data-anchor-id="observations-7">Observations:</h4>
<p>The histogram of domestic gross revenue shows a right-skewed distribution, indicating that most films generate low to moderate earnings. A significant number of movies earn little to no domestic gross, while only a few achieve high earnings.</p>
</section>
</section>
<section id="worldwide-gross" class="level3">
<h3 class="anchored" data-anchor-id="worldwide-gross">Worldwide gross</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>movies_modified <span class="sc">%&gt;%</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_histogram</span>(<span class="sc">~</span>worldwide_gross)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="observations-8" class="level4">
<h4 class="anchored" data-anchor-id="observations-8">Observations:</h4>
<p>The histogram of worldwide gross revenue displays a right-skewed distribution, similar to the other analysis. Most films earn relatively low revenue, with a significant number reporting little to no earnings. A small number of movies, however, achieve substantial worldwide gross, indicating the competitive landscape of the global film industry.</p>
</section>
</section>
<section id="profit-ratio" class="level3">
<h3 class="anchored" data-anchor-id="profit-ratio">Profit ratio</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>movies_modified <span class="sc">%&gt;%</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_histogram</span>(<span class="sc">~</span>profit_ratio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="observations-9" class="level4">
<h4 class="anchored" data-anchor-id="observations-9">Observations:</h4>
<p>Most data points are clustered near zero, with a sharp drop-off after the initial bar. The skewed nature of the graph suggests that the majority of movies have very low profit ratios, while only a few exhibit extreme values, indicating a highly unequal distribution of profits.</p>
</section>
</section>
</section>
<section id="research-questions" class="level2">
<h2 class="anchored" data-anchor-id="research-questions">Research Questions</h2>
<ol type="1">
<li><p>How do production budget and genre together influence the profit ratio of a movie?</p></li>
<li><p>How do different film distributors compare in profit ratios across various genres?</p></li>
<li><p>How do domestic gross and distributor type affect the overall worldwide gross of a movie?</p></li>
</ol>
</section>
<section id="plot" class="level2">
<h2 class="anchored" data-anchor-id="plot">Plot</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(movies_modified, <span class="fu">aes</span>(<span class="at">x =</span> genre, <span class="at">y =</span> profit_ratio)) <span class="sc">+</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(distributor))<span class="sc">+</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> <span class="st">"median"</span>, <span class="at">geom =</span> <span class="st">"bar"</span>) <span class="sc">+</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Profits made by film distributors"</span>, <span class="at">subtitle =</span> <span class="st">"Ratio of profits to budgets"</span>, <span class="at">x =</span> <span class="st">"Genre"</span>, <span class="at">y =</span> <span class="st">"Median Profit Ratio"</span>)<span class="sc">+</span>  </span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>median_profit_ratios <span class="ot">&lt;-</span> movies_modified <span class="sc">%&gt;%</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(genre) <span class="sc">%&gt;%</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">median_profit_ratio =</span> <span class="fu">median</span>(profit_ratio, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>median_profit_ratios</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  genre     median_profit_ratio
  &lt;fct&gt;                   &lt;dbl&gt;
1 Drama                 1.52e14
2 Comedy                1.87e14
3 Action                2.19e14
4 Horror                2.63e14
5 Adventure             2.49e14</code></pre>
</div>
</div>
</section>
<section id="plot-analysis" class="level2">
<h2 class="anchored" data-anchor-id="plot-analysis">Plot Analysis</h2>
<ol type="1">
<li><p>Type of plot.</p>
<p>The plot is a bar chart (using ggplot), specifically a dodge bar chart that displays the median profit ratio for different movie genres, separated by film distributor.</p></li>
<li><p>What are the variables used to plot this graph?</p>
<p>X-axis: Genre - the genre of the movie.</p>
<p>Y-axis: Median Profit Ratio - the median of the ratio of profits to budgets.</p>
<p>Faceting Variable: Distributor - the film distributor. Its used to create separate panels for each distributor.</p></li>
<li><p>If you were to invest in movie production ventures, which are the two best genres that you might decide to invest in?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(movies_modified, <span class="fu">aes</span>(<span class="at">x =</span> genre, <span class="at">y =</span> profit_ratio)) <span class="sc">+</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> <span class="st">"median"</span>, <span class="at">geom =</span> <span class="st">"bar"</span>) <span class="sc">+</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Profits made by film distributors"</span>, <span class="at">subtitle =</span> <span class="st">"Ratio of profits to budgets"</span>, <span class="at">x =</span> <span class="st">"Genre"</span>, <span class="at">y =</span> <span class="st">"Median Profit Ratio"</span>)<span class="sc">+</span>  </span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>If one were to invest in movie production ventures, the two best genres to consider would be Horror and Adventure. Based on the graph, Horror films show a notably high median profit ratio across various distributors, indicating their ability to generate substantial profits relative to their budgets. This genre has a dedicated fan base, and films often attract audiences, especially during peak seasons like Halloween. Investing in Horror films could bring in significant returns, given their financial success and proven ability to draw in crowds.</p>
<p>Adventure films also stand out in terms of profitability. The data suggests that they outperform genres like Drama, Action, and Comedy when considering the median profit ratios. This strong performance highlights a promising return on investment for films in this genre. Adventure films often feature engaging storytelling and visual effects, which can capture audiences and drive unimagnable box office success.</p>
<p>Interestingly, both Horror and Adventure genres have fewer films on the list compared to Drama, Action, and Comedy. Despite having less productions across all distributors, their higher profitability suggests a potential gap in the market. With fewer films, there is less competition, creating opportunities for small-budget productions. By focusing on these genres, investors can capitalize on their profitability while meeting audience demand for quality Horror and Adventur</p></li>
<li><p>Which R command might have been used to obtain the separate plots for each distributor?</p>
<p>The R command used to create separate plots for each distributor in the graph is:</p>
<p>facet_wrap(vars(distributor))</p>
<p>This command allows for the creation of multiple subplots (facets) in one plot, where each subplot corresponds to a different distributor, allowing for easier comparison across them.</p></li>
<li><p>If the original dataset had BUDGETS and PROFITS in separate columns, what preprocessing might have been done to achieve this plot?</p></li>
</ol>
</section>
<section id="insights" class="level2">
<h2 class="anchored" data-anchor-id="insights">Insights</h2>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>